[package]
name = "homer"
version = "0.1.0"
authors = ["Stefan Berggren <nsg@nsg.cc>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"

[dependencies.rocket_contrib]
version = "0.2.8"
default-features = false
features = ["handlebars_templates"]
